create table if not exists public.market_snapshots (
    id bigint generated by default as identity primary key,
    instrument text not null check (instrument in ('NIFTY', 'BANKNIFTY')),
    session_date date not null,
    source_timestamp timestamptz not null,
    received_at timestamptz not null,
    expiry date not null,
    source text not null,
    source_time_authoritative boolean not null default false,
    raw_sha256 text not null unique,
    raw_payload jsonb not null,
    normalized_payload jsonb not null,
    quality_payload jsonb not null,
    published boolean not null default true,
    created_at timestamptz not null default now()
);

create index if not exists market_snapshots_lookup
    on public.market_snapshots (instrument, session_date, source_timestamp desc);

alter table public.market_snapshots enable row level security;

drop policy if exists "published snapshots are readable" on public.market_snapshots;
create policy "published snapshots are readable"
    on public.market_snapshots for select
    to anon, authenticated
    using (published = true);

revoke insert, update, delete on public.market_snapshots from anon, authenticated;
grant select on public.market_snapshots to anon, authenticated;
